# Based on https://droogmic.github.io/microrust/getting-started/01.00.BUILD.html
# Automatically select this target when cargo building this project
[build]
# @TODO refer to the other project
target = "aarch64-unknown-none-softfloat"